swagger: "2.0"
info:
  description: ""
  version: "1.0.0"
  title: "KidsHaru - 아동 사진 공유 서비스"
  termsOfService: ""
  contact:
    email: "embrapers263@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "api.kidsharu.com"
basePath: "/v1"


tags:
- name: "auth"
  description: "Login and Register"
- name: "teacher"
  description: "Operations about teacher"
- name: "parent"
  description: "Operations about parent"


paths:
  /auth:
    get:
      tags:
      - "auth"
      summary: "Login"
      description: "로그인"
      parameters: 
      - in: "body"
        name: "body"
        required: true
        schema:
          type: "object"
          properties:
            id:
              type: "string"
              example: "example"
            password:
              type: "string"
              example: "03AC674216F3E15C761EE1A5E255F067953623C8B388B4459E13F978D7C846F4"
              description: "SHA256 Hashed Password"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/LoginResult"
        400:
          $ref: "#/definitions-response/InsufficientParameters"
        404:
          description: "아이디 또는 비밀번호가 틀렸을 경우"
          schema:
            type: "object"
            properties:
              msg:
                type: "string"
                example: "Invalid password"

  /auth/teacher:
    post:
      tags:
      - "auth"
      summary: "Register Of Teacher"
      description: "교사 회원가입"
      parameters: 
      - in: "body"
        name: "body"
        required: true
        schema:
          type: "object"
          properties:
            id:
              type: "string"
              example: "example"
            password:
              type: "string"
              example: "03AC674216F3E15C761EE1A5E255F067953623C8B388B4459E13F978D7C846F4"
              description: "SHA256 Hashed Password"
            name:
              type: "string"
              example: "홍길동"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/LoginResult"
        400:
          $ref: "#/definitions-response/InsufficientParameters"
        409:
          $ref: "#/definitions-response/AlreadyExist"

  /auth/parent:
    post:
      tags:
      - "auth"
      summary: "Register Of Parent"
      description: "학부모 회원가입"
      parameters: 
      - in: "body"
        name: "body"
        required: true
        schema:
          type: "object"
          properties:
            id:
              type: "string"
              example: "example"
            password:
              type: "string"
              example: "03AC674216F3E15C761EE1A5E255F067953623C8B388B4459E13F978D7C846F4"
              description: "SHA256 Hashed Password"
            invite_code:
              type: "string"
              example: "q1w2e3"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/LoginResult"
        400:
          $ref: "#/definitions-response/InsufficientParameters"
        409:
          $ref: "#/definitions-response/AlreadyExist"

definitions-response:
  InsufficientParameters:
    description: "클라이언트에서 보내준 데이터에서 빠진 부분이 있는 경우"
    schema:
      type: "object"
      properties:
        msg:
          type: "string"
          example: "There is no password"

  AlreadyExist:
    description: "이미 존재하는 아이디로 회원가입 하려는 경우"
    schema:
      type: "object"
      properties:
        msg:
          type: "string"
          example: "Already Exist ID"

definitions:
  LoginResult:
    type: "object"
    properties:
      access_token:
        type: "string"
        example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9"
      is_teacher:
        type: "boolean"
        example: true