swagger: "2.0"
info:
  description: ""
  version: "1.0.0"
  title: "KidsHaru - 아동 사진 공유 서비스"
  termsOfService: ""
  contact:
    email: "embrapers263@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "api.kidsharu.com"
basePath: "/v1"


tags:
- name: "auth"
  description: "로그인과 회원가입"
- name: "teacher"
  description: "교사의 원아, 앨범"
- name: "child"
  description: "원아 조회, 수정, 삭제"
- name: "album"
  description: "앨범 조회, 수정, 삭제"
- name: "picture"
  description: "사진의 원아 얼굴 정보 조회 및 수정"


paths:

  # auth
  /teachers:
    post:
      tags:
      - "auth"
      summary: "교사 회원가입"
      parameters:
      - $ref: "#/def-req-body/register_teacher"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/LoginResult"
        400:
          $ref: "#/def-res/InsufficientParameters"
        409:
          $ref: "#/def-res/AlreadyExistID"
        500:
          $ref: "#/def-res/InternalServerError"

  /parents:
    post:
      tags:
      - "auth"
      summary: "학부모 회원가입"
      parameters:
      - $ref: "#/def-req-body/register_parent"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/LoginResult"
        400:
          $ref: "#/def-res/InsufficientParameters"
        409:
          $ref: "#/def-res/AlreadyExistID"
        500:
          $ref: "#/def-res/InternalServerError"

  /teachers/auth:
    post:
      tags:
      - "auth"
      summary: "교사 로그인"
      parameters:
      - $ref: "#/def-req-body/login"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/LoginResult"
        400:
          $ref: "#/def-res/InsufficientParameters"
        404:
          $ref: "#/def-res/IDorPasswordWrong"
        500:
          $ref: "#/def-res/InternalServerError"

  /parents/auth:
    post:
      tags:
      - "auth"
      summary: "학부모 로그인"
      parameters:
      - $ref: "#/def-req-body/login"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/LoginResult"
        400:
          $ref: "#/def-res/InsufficientParameters"
        404:
          $ref: "#/def-res/IDorPasswordWrong"
        500:
          $ref: "#/def-res/InternalServerError"

  # teacher
  /teachers/{teacher_id}/children:
    get:
      tags:
      - "teacher"
      summary: "교사의 원아 리스트"
      parameters:
      - $ref: "#/def-req-path/teacher_id"
      responses:
        200:
          description: "Success"
          schema:
            type: array
            items:
              $ref: "#/definitions/Child"
        400:
          $ref: "#/def-res/InsufficientParameters"
        500:
          $ref: "#/def-res/InternalServerError"
    post:
      tags:
      - "teacher"
      summary: "교사의 원아 추가"
      parameters:
      - $ref: "#/def-req-path/teacher_id"
      - $ref: "#/def-req-body/child"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/Child"
        400:
          $ref: "#/def-res/InsufficientParameters"
        409:
          $ref: "#/def-res/AlreadyExist"
        500:
          $ref: "#/def-res/InternalServerError"

  /teachers/{teacher_id}/albums:
    get:
      tags:
      - "teacher"
      summary: "교사의 앨범 리스트"
      parameters:
      - $ref: "#/def-req-path/teacher_id"
      responses:
        200:
          description: "Success"
          schema:
            type: array
            items:
              $ref: "#/definitions/AlbumPreview"
        400:
          $ref: "#/def-res/InsufficientParameters"
        500:
          $ref: "#/def-res/InternalServerError"
    post:
      tags:
      - "teacher"
      summary: "교사의 앨범 추가"
      parameters:
      - $ref: "#/def-req-path/teacher_id"
      - $ref: "#/def-req-body/album"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/Album"
        400:
          $ref: "#/def-res/InsufficientParameters"
        409:
          $ref: "#/def-res/AlreadyExist"
        500:
          $ref: "#/def-res/InternalServerError"

  # child
  /children/{child_id}:
    get:
      tags:
      - "child"
      summary: "원아의 자세한 정보"
      parameters:
      - $ref: "#/def-req-path/child_id"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/Child"
        400:
          $ref: "#/def-res/InsufficientParameters"
        404:
          $ref: "#/def-res/NotExists"
        500:
          $ref: "#/def-res/InternalServerError"
    put:
      tags:
      - "child"
      summary: "원아의 정보 수정"
      parameters:
      - $ref: "#/def-req-path/child_id"
      - $ref: "#/def-req-body/child"
      responses:
        204:
          description: "Success"
        400:
          $ref: "#/def-res/InsufficientParameters"
        404:
          $ref: "#/def-res/NotExists"
        500:
          $ref: "#/def-res/InternalServerError"
    delete:
      tags:
      - "child"
      summary: "원아 삭제"
      parameters:
      - $ref: "#/def-req-path/child_id"
      responses:
        204:
          description: "Success"
        400:
          $ref: "#/def-res/InsufficientParameters"
        404:
          $ref: "#/def-res/NotExists"
        500:
          $ref: "#/def-res/InternalServerError"

  # album
  /albums/{album_id}:
    get:
      tags:
      - "album"
      summary: "앨범의 자세한 정보"
      parameters:
      - $ref: "#/def-req-path/album_id"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/Album"
        400:
          $ref: "#/def-res/InsufficientParameters"
        404:
          $ref: "#/def-res/NotExists"
        500:
          $ref: "#/def-res/InternalServerError"
    put:
      tags:
      - "album"
      summary: "앨범의 정보 수정"
      parameters:
      - $ref: "#/def-req-path/album_id"
      - $ref: "#/def-req-body/album"
      responses:
        204:
          description: "Success"
        400:
          $ref: "#/def-res/InsufficientParameters"
        404:
          $ref: "#/def-res/NotExists"
        500:
          $ref: "#/def-res/InternalServerError"
    delete:
      tags:
      - "album"
      summary: "앨범 삭제"
      parameters:
      - $ref: "#/def-req-path/album_id"
      responses:
        204:
          description: "Success"
        400:
          $ref: "#/def-res/InsufficientParameters"
        404:
          $ref: "#/def-res/NotExists"
        500:
          $ref: "#/def-res/InternalServerError"

  # picture
  /albums/{album_id}/pictures/{picture_id}:
    get:
      tags:
      - "picture"
      summary: "사진의 URL 및 원아 얼굴 정보"
      parameters:
      - $ref: "#/def-req-path/album_id"
      - $ref: "#/def-req-path/picture_id"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/Picture"
        400:
          $ref: "#/def-res/InsufficientParameters"
        404:
          $ref: "#/def-res/NotExists"
        500:
          $ref: "#/def-res/InternalServerError"
    put:
      tags:
      - "picture"
      summary: "사진의 원아 얼굴 정보 수정"
      parameters:
      - $ref: "#/def-req-path/album_id"
      - $ref: "#/def-req-path/picture_id"
      - $ref: "#/def-req-body/face"
      responses:
        204:
          description: "Success"
        400:
          $ref: "#/def-res/InsufficientParameters"
        404:
          $ref: "#/def-res/NotExists"
        500:
          $ref: "#/def-res/InternalServerError"

# def-req-path =====================================================================
def-req-path:
  teacher_id:
    name: "teacher_id"
    in: path
    description: "teacher_id"
    required: true
    type: integer
  child_id:
    name: "child_id"
    in: "path"
    description: "child_id"
    required: true
    type: integer
  album_id:
    name: "album_id"
    in: "path"
    description: "album_id"
    required: true
    type: integer
  picture_id:
    name: "picture_id"
    in: "path"
    description: "picture_id"
    required: true
    type: string

# def-req-body =====================================================================
def-req-body:
  register_teacher:
    name: "body"
    in: "body"
    required: true
    schema:
      type: object
      properties:
        id:
          $ref: "#/def-property/id"
        password:
          $ref: "#/def-property/password"
        name:
          $ref: "#/def-property/name"
  register_parent:
    name: "body"
    in: "body"
    required: true
    schema:
      type: object
      properties:
        id:
          $ref: "#/def-property/id"
        password:
          $ref: "#/def-property/password"
        invite_code:
          $ref: "#/def-property/invite_code"
  login:
    name: "body"
    in: "body"
    required: true
    schema:
      type: object
      properties:
        id:
          $ref: "#/def-property/id"
        password:
          $ref: "#/def-property/password"
  child:
    in: "body"
    name: "body"
    required: true
    schema:
      type: object
      properties:
        name:
          $ref: "#/def-property/name"
        contact:
          $ref: "#/def-property/contact"
  album:
    name: "body"
    in: "body"
    required: true
    schema:
      type: object
      properties:
        title:
          $ref: "#/def-property/album_title"
        content:
          $ref: "#/def-property/album_content"
  face:
    name: "body"
    in: "body"
    required: true
    schema:
      $ref: "#/definitions/Face"

# definitions ====================================================================
definitions:
  LoginResult:
    type: object
    properties:
      access_token:
        $ref: "#/def-property/access_token"
  Child:
    type: object
    properties:
      child_id:
        $ref: "#/def-property/child_id"
      name:
        $ref: "#/def-property/name"
      contact:
        $ref: "#/def-property/contact"
  AlbumPreview:
    type: object
    properties:
      album_id:
        $ref: "#/def-property/album_id"
      title:
        $ref: "#/def-property/album_title"
      content:
        $ref: "#/def-property/album_content"
      cover_img:
        $ref: "#/def-property/picture_url"
  Album:
    type: object
    properties:
      album_id:
        $ref: "#/def-property/album_id"
      title:
        $ref: "#/def-property/album_title"
      content:
        $ref: "#/def-property/album_content"
      cover_img:
        $ref: "#/def-property/picture_url"
      pictures:
        type: array
        items:
          $ref: "#/definitions/PicturePreview"
  PicturePreview:
    type: object
    properties:
      album_id:
        $ref: "#/def-property/album_id"
      picture_id:
        $ref: "#/def-property/picture_id"
      picture_url:
        $ref: "#/def-property/picture_url"
  Picture:
    type: object
    properties:
      album_id:
        $ref: "#/def-property/album_id"
      picture_id:
        $ref: "#/def-property/picture_id"
      picture_url:
        $ref: "#/def-property/picture_url"
      faces:
        type: array
        items:
          $ref: "#/definitions/Face"
  Face:
    type: object
    properties:
      album_id:
        $ref: "#/def-property/album_id"
      picture_id:
        $ref: "#/def-property/picture_id"
      child_id:
        $ref: "#/def-property/child_id"
      child_name:
        $ref: "#/def-property/name"
      rect_x:
        $ref: "#/def-property/rect_x"
      rect_y:
        $ref: "#/def-property/rect_y"
      rect_width:
        $ref: "#/def-property/rect_width"
      rect_height:
        $ref: "#/def-property/rect_height"

# def-property ====================================================================
def-property:
  id:
    type: string
    example: "example"
  password:
    type: string
    example: "03AC674216F3E15C761EE1A5E255F067953623C8B388B4459E13F978D7C846F4"
    description: "SHA256 Hashed Password"
  invite_code:
    type: string
    example: "q1w2e3"
  access_token:
    type: string
    example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9"

  child_id:
    type: int
    example: 1
  name:
    type: string
    example: "박철수"
  contact:
    type: string
    example: "010-1234-1234"

  album_id:
    type: int
    example: 1
  album_title:
    type: string
    example: "7월 15일 안전 체험관 견학"
  album_content:
    type: string
    example: "우리 햇님반 어린이들과 안전 체험관 견학을 갔다왔어요~~"

  picture_id:
    type: int
    example: 1
  picture_url:
    type: string
    example: "https://example.com/asdf.jpg"

  rect_x:
    type: int
    example: 24
    description: "단위: pixel"
  rect_y:
    type: int
    example: 34
    description: "단위: pixel"
  rect_width:
    type: int
    example: 125
    description: "단위: pixel"
  rect_height:
    type: int
    example: 146
    description: "단위: pixel"


# def-res ======================================================================
def-res:
  AlreadyExistID:
    description: "이미 존재하는 아이디로 회원가입 하려는 경우"
    schema:
      type: object
      properties:
        msg:
          type: string
          example: "Already Exist ID"
  IDorPasswordWrong:
    description: "아이디 또는 비밀번호가 틀렸을 경우"
    schema:
      type: object
      properties:
        msg:
          type: string
          example: "Invalid password"
  InsufficientParameters:
    description: "클라이언트에서 보내준 데이터에서 빠진 부분이 있는 경우"
    schema:
      type: object
      properties:
        msg:
          type: string
          example: "There is no [field name] in parameters"
  AlreadyExist:
    description: "이미 존재하는 경우"
    schema:
      type: object
      properties:
        msg:
          type: string
          example: "Already Exist"
  NotExists:
    description: "존재 하지 않는 경우"
    schema:
      type: object
      properties:
        msg:
          type: string
          example: "There is no [field name] which is [field value] in database"
  InternalServerError:
    description: "예상치 못한 서버 에러가 발생한 경우"
    schema:
      type: object
      properties:
        msg:
          type: string
          example: "~~"
